# Generated by Django 4.1.7 on 2023-06-02 13:51

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('ready_time', models.PositiveSmallIntegerField()),
                ('img', models.FileField(default='default.png', upload_to=product.models.upload_to)),
            ],
            options={
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
